### ISSUE TITLE
Roadmap for TS to Dart conversion 

### ISSUE THREAD

**Issue by Arenukvern** [uhst/uhst-client-flutter#1]
Conversion milestones

**Primitive conversion from TS to Dart**
- [x] Develop structure as it is described in Helper documentation section
- [x] Root interfaces and classes
- [x] Models
- [x] Contracts
- [x] Errors
- [x] Exceptions
- [x] UhstHost
- [x] WebRTCSocket
- [x] Dart adaptation & refactoring 

**Example and testing**
- [x] web
- [x] android
- [x] linux
- [x] windows
- [ ] ios (?)
- [ ] macos (?)
- [x] Tests (?)
- [x] Prototype Approval
----

**Release Candidate 2:**

- [x] Code optimization & refactoring 
- [x] Optimization Approval
- [x] ReadMe
- [x] Documentation
- [x] Approval for Release Candidate
 
----

**Please notice:**
all dates are subject to change and for development purposes only

To check repository before publish:
```shell
flutter pub publish --dry-run
```

### Package Design
Main document:
https://flutter.dev/docs/development/packages-and-plugins/developing-packages

Related:
https://dart.dev/guides/libraries/create-library-packages#what-makes-a-library-package
https://dart.dev/tools/pub/package-layout
https://dart.dev/guides/libraries/create-library-packages#what-makes-a-library-package

### Documentation Design
https://dart.dev/guides/language/effective-dart/documentation

**Comment by dimitrovs** [comment]
Are we going to use the JS library in webview or write native?

**Comment by Arenukvern** [comment]
@dimitrovs I will try to write native as possible.
